[package]
name = "prismatic_visualizer"
version = "0.2.4"
edition = "2021"
authors = ["Digital Greenery"]

[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

[dependencies]
bevy = "0.15.0"
bevy_egui = "0.31.1"
prismatic_color = { git = "https://github.com/digitalgreenery/prismatic-color.git" }
wasm-bindgen = "0.2.97"
bytemuck = "1.20.0"