[package]
name = "spherical_rgb"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12"
egui = "0.24"
bevy_egui = "0.23"
lazy_static = "1.4"
