[package]
name = "prismatic_visualizer"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.15.0"
egui = "0.29.1"
bevy_egui = "0.31.1"
prismatic_color = { git = "https://github.com/digitalgreenery/prismatic-color.git" }
wasm-bindgen = "0.2.97"
bytemuck = "1.20.0"