[package]
name = "spherical_rgb_visualizer"
version = "0.1.4"
edition = "2021"
authors = ["Digital Greenery"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12"
egui = "0.24"
bevy_egui = "0.23"
spherical_rgb = { path = "../spherical_rgb"}
wasm-bindgen = "0.2.87"